### ISSUE TITLE
Trying to connect with safe network

### ISSUE THREAD

**Issue by macdasi** [maidsafe/safe_launcher#147] opened 2016-06-09 09:23 UTC
![image](https://cloud.githubusercontent.com/assets/6370865/15924762/7725caa0-2e3c-11e6-8885-0dce61dace44.png)

UI-log 

{"level":"debug","message":"Starting FFI worker client","timestamp":"2016-06-09T09:18:11.487Z"}
{"level":"debug","message":"Sending FFI initialisation request","timestamp":"2016-06-09T09:18:11.495Z"}
{"level":"debug","message":"Sending message to FFI [object Object]","timestamp":"2016-06-09T09:18:11.495Z"}
{"level":"debug","message":"Message callback IDGjDr1GCe4tQntLLTr17+K8n07efJ9ICPlnaNpNfXZNANHRMPac4AJ7Hmqx58Wo4EyuSaTU6oJaJ9mdRi56Hw9A== [object Object]","timestamp":"2016-06-09T09:18:11.514Z"}
{"level":"debug","message":"Application starting","timestamp":"2016-06-09T09:18:11.516Z"}
{"level":"info","message":"Starting proxy server","timestamp":"2016-06-09T09:18:11.615Z"}
{"level":"debug","message":"Proxy Server - onMessage event - recieved - {\"status\":true,\"data\":\"Proxy Started\"}","timestamp":"2016-06-09T09:18:11.733Z"}
{"level":"info","message":"Proxy server started","timestamp":"2016-06-09T09:18:11.733Z"}
{"level":"info","message":"Stopping proxy server","timestamp":"2016-06-09T09:21:13.531Z"}
{"level":"debug","message":"Closing FFI worker client","timestamp":"2016-06-09T09:21:13.546Z"}
{"level":"info","message":"Proxy server stopped","timestamp":"2016-06-09T09:21:13.546Z"}
{"level":"warn","message":"Starting FFI worker client closed already","timestamp":"2016-06-09T09:21:13.546Z"}

client log

DEBUG 12:18:14.182543400 [crust::service service.rs:105] Network name: Some("client_test_2")
WARN 12:18:35.212180600 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:18:35.212180600 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:18:56.239636800 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:18:56.239636800 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:19:17.242445200 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:19:17.242445200 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:19:38.214595400 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:19:38.214595400 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:19:59.265539200 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:19:59.265539200 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:20:20.252947300 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:20:20.252947300 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
DEBUG 12:20:20.252947300 [routing::core core.rs:1087] Disconnected(c839a0..) Finished bootstrapping.

**Comment by macdasi** [comment] 2016-06-09 09:44
After configuring a proxy @ window 7 internet option 
according to :
https://maidsafe.readme.io/docs/proxy-setup#windows-7-proxy-setup

the logs are : 

DEBUG 12:41:52.641006500 [crust::service service.rs:105] Network name: Some("client_test_2")
WARN 12:42:13.697330500 [crust::connection connection.rs:173] TCP direct connect failed: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
WARN 12:42:13.697330500 [crust::bootstrap bootstrap.rs:119] Error connecting to bootstrap peer: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

{"level":"debug","message":"Starting FFI worker client","timestamp":"2016-06-09T09:41:49.915Z"}
{"level":"debug","message":"Sending FFI initialisation request","timestamp":"2016-06-09T09:41:49.924Z"}
{"level":"debug","message":"Sending message to FFI [object Object]","timestamp":"2016-06-09T09:41:49.924Z"}
{"level":"debug","message":"Message callback IDGjDr1GCe4tQntLLTr17+K8n07efJ9ICPlnaNpNfXZNANHRMPac4AJ7Hmqx58Wo4EyuSaTU6oJaJ9mdRi56Hw9A== [object Object]","timestamp":"2016-06-09T09:41:49.943Z"}
{"level":"debug","message":"Application starting","timestamp":"2016-06-09T09:41:49.945Z"}
{"level":"info","message":"Starting proxy server","timestamp":"2016-06-09T09:41:50.036Z"}
{"level":"debug","message":"Proxy Server - onMessage event - recieved - {\"status\":true,\"data\":\"Proxy Started\"}","timestamp":"2016-06-09T09:41:50.166Z"}
{"level":"info","message":"Proxy server started","timestamp":"2016-06-09T09:41:50.166Z"}

**Comment by Viv-Rajkumar** [comment] 2016-06-09 12:01
Thanks for the report. In this case:

Connecting to the network should have nothing to do with setting up a proxy.

I'm not able to reproduce this issue locally though. Just downloaded [Launcher v0.4.5 for Windows](https://github.com/maidsafe/safe_launcher/releases/tag/0.4.5) and running the binary connected fine to the network.

I did have to choose allow access to the popup that comes up asking for network access permission. Not sure if you have something in your firewall maybe that blocks the binary?

**Comment by macdasi** [comment] 2016-06-09 12:14
Keep in mind that I'm connected in an office that may have some kind of security / firewall on the network. From my house it's ok.

**Comment by alkchr** [comment] 2016-06-26 18:16
Looks like I have a similar issue with the latest `v0.4.5` launcher on GNU/Linux. Logs:
**Client.log**
```
DEBUG 23:51:01.728880683 [crust::main::service service.rs:552] Network name: Some("2016_06_14_test_network_4")
DEBUG 23:51:12.829396988 [routing::core core.rs:1021] Disconnected(0863bc..) Failed to bootstrap.
```
**safe_launcher_ui.log**
```
{"level":"debug","message":"Starting FFI worker client","timestamp":"2016-06-26T17:51:01.288Z"}
{"level":"debug","message":"Sending FFI initialisation request","timestamp":"2016-06-26T17:51:01.311Z"}
{"level":"debug","message":"Sending message to FFI [object Object]","timestamp":"2016-06-26T17:51:01.312Z"}
{"level":"debug","message":"Message callback IDGjDr1GCe4tQntLLTr17+K8n07efJ9ICPlnaNpNfXZNANHRMPac4AJ7Hmqx58Wo4EyuSaTU6oJaJ9mdRi56Hw9A== [object Object]","timestamp":"2016-06-26T17:51:01.370Z"}
{"level":"debug","message":"Application starting","timestamp":"2016-06-26T17:51:01.382Z"}
{"level":"info","message":"Starting proxy server","timestamp":"2016-06-26T17:51:01.723Z"}
{"level":"debug","message":"Proxy Server - onMessage event - recieved - {\"status\":true,\"data\":\"Proxy Started\"}","timestamp":"2016-06-26T17:51:02.112Z"}
{"level":"info","message":"Proxy server started","timestamp":"2016-06-26T17:51:02.113Z"}
```

The worst part is how the client app handles that. No error messages, no details or clues on what's going on (apart from the static message: "waiting for establishing connection"). Nothing just works.

**Comment by krishnaIndia** [comment] 2016-06-26 18:50
@alkchr the test network is down and you wont be able to connect to the test network 4. You can read the forum [post](https://forum.safenetwork.io/t/test-network-4-complete/10011/) to know more. But as you said, we are looking to improve the UX in these areas. We will be rolling out UI updates in couple of weeks to reduce the UX issues faced.

**Comment by krishnaIndia** [comment] 2016-08-23 16:02
This should be fixed in the latest version. If it persists, we can move to this issue to [crust ](https://github.com/maidsafe/crust) to get it fixed

**Closed by krishnaIndia** 2016-08-23 16:02 UTC
