### ISSUE TITLE
0.7.1 Launcher seizing up after a couple of hours running + new login

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#216] opened 2016-08-01 22:05 UTC
The launcher is seizing up after running a long while ~2hrs without being logged in, it becomes unresponsive then when I do log in. That follows a lot of activity scanning guessed public websites.

Edit: removed confusion re metrics.

I'm not sure if it's unresponsive immediately or that happens only after the Demo App asks for authorisation but the auth box doesn't appear and switching to the other tabs in the launcher doesn't respond. I've seen this now on a few occasions but only after having it run for a long while. I wonder on a previous occasion the launcher did respond eventually with a jumping through the tabs selected all of a rush but only after a minute or so of being stuck. While this occurs nothing apparent in the launcher terminal.

This occasion I again had to force launcher closure with Ctrl-C.. yes, I expect there's a better way but that left two processes left running after forced closure of launcher:
/SAFE/safe_launcher-v0.7.1-linux-x64/safe_launcher /home/davidpbrown/SAFE/safe_launcher-v0.7.1-linux-x64/resources/app.asar/api/ffi/worker.js
/home/davidpbrown/SAFE/safe_launcher-v0.7.1-linux-x64/safe_launcher /home/davidpbrown/SAFE/safe_launcher-v0.7.1-linux-x64/resources/app.asar/server/web_proxy.js --proxyPort 8101 --serverPort 8100

Restarting the launcher having cleared down processes, works fine again and just as fast as ever; so, it's as if there is some accumulated overhead or confusion occurring.

Potentially this is then something following from length of time open or it's relative to the amount of activity and GETs, which in this case would be 1000+ via wget requests. There's no indication of a problem until after successful login.

**Comment by krishnaIndia** [comment] 2016-08-02 10:37
@davidpbrown, is it possible to reproduce this issue and paste the logs here?

I will also try to replicate this from my end based on  your inputs. In case, if you could reproduce this issue again, please do share the logs which will help us to resolve it quicker hopefully.

> This occasion I again had to force launcher closure with Ctrl-C.. yes, I expect there's a better way but that left two processes left running after forced closure of launcher:
/SAFE/safe_launcher-v0.7.1-linux-x64/safe_launcher /home/davidpbrown/SAFE/safe_launcher-v0.7.1-linux-x64/resources/app.asar/api/ffi/worker.js
/home/davidpbrown/SAFE/safe_launcher-v0.7.1-linux-x64/safe_launcher /home/davidpbrown/SAFE/safe_launcher-v0.7.1-linux-x64/resources/app.asar/server/web_proxy.js --proxyPort 8101 --serverPort 8100

This issue will be fixed in the next update of the launcher.

**Comment by davidpbrown** [comment] 2016-08-02 16:57
Looking at this again, I think the PUTs are correct; so, ignore that. I got confused thinking it was talking of the session but having logged into that account that will simply relate to the history of that account.

The freezing is something I've seen now several times, so it's certainly reproducible.. what I'll do is run the launcher for a couple of hours without activity and also with activity and see which is different.

**Comment by davidpbrown** [comment] 2016-08-02 20:30
So, two similar laptops. On one I ran a launcher with no activity for as long as the other and the logged in and it worked as normal. On the other I ran the usual scan of urls and experienced the same issues.

The Client.log became 9.8MB. I'll attach the last ~20mins of that and also a matching amount of the launcher terminal output. Those then capture from the end of getting a long list of urls, through logging in and the launcher being sticky.
See [part-Client.txt] and [part-launcher-terminal-output.txt]
[part-Client.txt](https://github.com/maidsafe/safe_launcher/files/398038/part-Client.txt)
[part-launcher-terminal-output.txt](https://github.com/maidsafe/safe_launcher/files/398039/part-launcher-terminal-output.txt)

What I forgot to try is to check that the launcher tabs were alive before logging in.. but since the account login screen was as responsive as ever, I didn't think to do that and expect there isn't a problem at that point.

Having logged in, I then run the Demo App and it waits for authorisation but nothing appears to happen..
See the first screenshot:[Screenshot at 2016-08-02 21:01:19.png]
![screenshot at 2016-08-02 21 01 19](https://cloud.githubusercontent.com/assets/1708690/17343881/cefeedfc-58f7-11e6-8a09-8cc76d9444de.png)

I shut down the Demo App to restart it and around the same time the launcher terminal throws this:

```
DEBUG 21:0:53.238 - Authorised request ::/auth
DEBUG 21:0:53.241 - Decrypted session id :: undefined
WARN 21:0:53.255 - Session ID not found
DEBUG 21:0:54.566 - Authorised request ::/auth
DEBUG 21:0:54.571 - Decrypted session id :: undefined
WARN 21:0:54.572 - Session ID not found
DEBUG 21:0:54.631 - Unauthorised request ::/auth
DEBUG 21:0:54.755 - Authorisation request received
DEBUG 21:0:54.758 - Emitting event for auth request received
```

and the Authorise Request pops up.. but is unresponsive.. again the impression that the launcher is sticky.

See second screenshot:[Screenshot at 2016-08-02 21:02:37.png]
![screenshot at 2016-08-02 21 02 37](https://cloud.githubusercontent.com/assets/1708690/17343892/dadcbd0c-58f7-11e6-9f2c-0731b5ebfc8d.png)

I wait a while expecting perhaps it might authorise but nothing and trying again the [deny allow] is not obviously noting the mouse click to those.

I put the screenshots there with their timestamp, hoping perhaps the timestamp in the logs will match to give an indication of what occured.

So, I tried three times the Demo App, it seemed to be on the second occation that the terminal emitted that above, where launcher terminal didn't seem to acknowledge the Demo App on the other two occasions it was started. The Demo App then appeared to receive no reply on all three occasions.

Whether it is the case that a reply would have arrived eventually is beyond the point that the user experience is badly affected by launcher delays and to the point it's unclear to me that it was trying to respond.. if it was busy, I'd expect more output and response to environment than it was giving.. not outputting anything when Demo App started I wondered perhaps was a message not received.

If you do want the whole 9.8MB Client.log, let me know but the start of it is just a run of get requests and nothing extraordinary.

**Comment by krishnaIndia** [comment] 2016-08-04 08:59
Thanks for the logs, @davidpbrown. The logs seems to be fine. I doubt it can be a UI related issue. Will try to follow the instructions to reproduce this issue at my end and get this fixed. I will look into this today.

**Comment by davidpbrown** [comment] 2016-08-04 20:39
So, the sticky in the launcher is not to do with the Demo App.

All tabs in the launcher are responsive to the end of the scanning script and up to the point of logging in. Immediately after the login the launcher is stuck.. I stuck with it. htop suggests a launcher process is chewing up 104% CPU when tabs are selected. Outside that selecting a tab, nothing extraordinary on the CPU useage.

Specifically:

Moving [Account] -> [Settings] takes 9 secs
Moving [Settings] -> [Account] takes 61 secs

Moving [Account] -> [Dashboard] takes 9 secs
Moving [Dashboard] -> [Account] takes 61 secs

Moving [Account] -> [Logs] takes 9 secs
Moving [Logs] -> [Account] takes 61 secs

Moving [Account] -> [Help] takes 8 secs
Moving [Help] -> [Account] takes 61 secs

Any other tab switch that does not involve [Account] tab works fine.

So, I wonder if it's to do with the Authorised Apps element - though none are authorised.. or some other element in the Account tab. It's odd that the delay is not simply on entering the Account tab but also apparently on leaving it too.

One step forward perhaps.. but why should that occur only after having given the launcher some work to do? Through that script running, activity is through to the terminal.. I've not used the launcher while it's run in any extraordinary way.

It might be the proxy?.. I didn't have patience to stick with it to use the Demo App and update the directory but I did get to the point of it's having authorised the Demo App. The initial step in the Demo App appeared very delayed and I worried the proxy/launcher might cause a trouble uploading a file, so stopped there.

**Comment by krishnaIndia** [comment] 2016-08-05 04:59
I tried to reproduce this issue, I did find some lag. I will drill more into this one today again. 
Thanks, @davidpbrown

**Comment by krishnaIndia** [comment] 2016-08-05 05:05
Can you also share your system configuration if possible?

**Comment by davidpbrown** [comment] 2016-08-05 06:20
If it was only on entering the Account tab, I'd wonder how the launcher kept track of a authorisations and if it was scanning a large Client.log.. but unclear if that would be it.

System is HP255 laptop:

Linux Mint: Release Linux Mint 17.3 Rosa 64-bit
Kernel Linux 3.19.0-32-generic x86_64
MATE 1.12.0

Memory: 3.5 GiB
Processor: AMD E1-1500 APU with Radeon(tm) HD Graphics × 2

**Comment by krishnaIndia** [comment] 2016-08-05 06:32
Thanks for sharing the config, @davidpbrown. We don't scan logs file from launcher, so definitely that is not the cause. I ll update back as soon as I spot the actual cause.

**Closed** 2016-08-11 11:40 UTC
Labels: in progress
