### ISSUE TITLE
Testnet3:Linux upload of directory beyond 5MB fails in Launcher with panic and PoisonError

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_launcher#139] opened 2016-05-17 19:16 UTC
While others suggest that attempting file directory upload beyond 5MB will give an error, I got no error initially, trying to upload 7.1MB directory with the largest file being just 1.3MB. It just tries and then fails with an error.

So, eventually at ~90% the launcher gave an error:
````
thread '<unnamed>' panicked at '

 ====================================================================================================
| Result evaluated to Err: CoreError::MutationFailure::{ reason: LowBalance, data: ImmutableData f7ad..} |
 ====================================================================================================

', src/core/self_encryption_storage.rs:59
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at '

 ======================================================
| Result evaluated to Err: "PoisonError { inner: .. }" |
 ======================================================

', src/core/self_encryption_storage.rs:59
````

I did that twice and got the same result.

Expected to see: upload in the Demo app note that files summed to beyond the available capacity or otherwise fails gracefully with error indicating how much had not succeeded.
Instead saw: the Demo app did nothing but stall, while the launcher noted there was a problem.

Putting this here as it's the launcher that is noting the error as panic with PoisonError rather than the Demo app itself, so expecting the Launcher is not handling this ideally.

**Comment by krishnaIndia** [comment] 2016-05-20 09:46
Thanks @davidpbrown. The trace of the issue is helpful. We have identified the issue and would be getting fixed in the next release, until then will leave this issue open.

**Comment by krishnaIndia** [comment] 2016-07-15 18:56
This issue is resolved, @davidpbrown. Thanks again!

**Closed by krishnaIndia** 2016-07-15 18:56 UTC
